### PR TITLE
fix: support `module: NodeNext` and `Node16` 

### LINKED ISSUE #11: Doesn't support new "module" values like "nodenext" and "node16"
```
Error: Non-support module kind: 199
    at getModuleType (file:///home/fabis/Code/speckle/speckle-server/node_modules/tsconfig-to-dual-package/module/tsconfig-to-dual-package.js:75:11)
    at file:///home/fabis/Code/speckle/speckle-server/node_modules/tsconfig-to-dual-package/module/tsconfig-to-dual-package.js:114:23
    at Array.map (<anonymous>)
    at tsconfigToDualPackages (file:///home/fabis/Code/speckle/speckle-server/node_modules/tsconfig-to-dual-package/module/tsconfig-to-dual-package.js:89:54)
    at async Module.run (file:///home/fabis/Code/speckle/speckle-server/node_modules/tsconfig-to-dual-package/module/cli.js:49:5)
```

### PR DESCRIPTION
**Pull request by azu**
- fix #11

### CODE REVIEW

File: src/tsconfig-to-dual-package.ts [hunk 1]
```diff
@@ -78,17 +99,31 @@ export const createModuleTypePackage = async ({
...
     // TODO: get more better way
     if (moduleKind >= ts.ModuleKind.ES2015 && moduleKind <= ts.ModuleKind.ESNext) {
         return "module";
+    } else if (moduleKind >= ts.ModuleKind.Node16 && moduleKind <= ts.ModuleKind.NodeNext) {
+        // use package.json's type
+        // if type is not set, use commonjs
+        // > The emitted JavaScript uses either CommonJS or ES2020 output depending on the file extension and the value of the type setting in the nearest package.json. Module resolution also works differently.
+        // https://www.typescriptlang.org/tsconfig#node16nodenext-nightly-builds
+        // https://www.typescriptlang.org/docs/handbook/esm-node.html
+        return packageType ?? "commonjs";
```
Comment (azu) [inline src/tsconfig-to-dual-package.ts:118]: https://github.com/azu/tsc-node-next
default is "commonjs"
